name: blt-proc
channels:
  - conda-forge
dependencies:
  - python=3.10
  - mercurial
  - cmocean
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - gsw
  - scipy
  - tqdm
  - xarray
  - cftime
  - nc-time-axis
  - requests
  - statsmodels
  - jupytext
  - pip
  - pip:
    - pyrsktools
    - hg+https://currents.soest.hawaii.edu/hgstage/pycurrents@333d57320873
    - "-e /Users/gunnar/Projects/python/gadcp"
    - "-e /Users/gunnar/Projects/python/gvpy"
    - "-e /Users/gunnar/Projects/python/ctdproc"
    - "-e /Users/gunnar/Projects/python/rbrmoored"
    - "-e /Users/gunnar/Projects/python/sbemoored"
    - "-e /Users/gunnar/Projects/python/underway"
    - "-e ."
    # - "-e git+https://github.com/gunnarvoet/gvpy.git@master#egg=gvpy"
